2022/11/23 10:48:09 [error] 9568#0: *1 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: module 'mobdebug' not found:
	no field package.preload['mobdebug']
	no file '/cygdrive/d/code1/nginx-master/conf/x-waf/mobdebug.lua'
	no file '/usr/local/lib/lua/mobdebug.lua'
	no file './mobdebug.lua'
	no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug/init.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug/init.lua'
	no file './mobdebug.so'
	no file '/usr/local/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/LuaJIT/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: in main chunk, client: 127.0.0.1, server: localhost, request: "GET /hello HTTP/1.1", host: "localhost"
2022/11/23 10:48:09 [error] 9568#0: *1 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: module 'mobdebug' not found:
	no field package.preload['mobdebug']
	no file '/cygdrive/d/code1/nginx-master/conf/x-waf/mobdebug.lua'
	no file '/usr/local/lib/lua/mobdebug.lua'
	no file './mobdebug.lua'
	no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug/init.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug/init.lua'
	no file './mobdebug.so'
	no file '/usr/local/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/LuaJIT/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: in main chunk, client: 127.0.0.1, server: localhost, request: "GET /hello HTTP/1.1", host: "localhost"
2022/11/23 10:48:10 [error] 9568#0: *2 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: module 'mobdebug' not found:
	no field package.preload['mobdebug']
	no file '/cygdrive/d/code1/nginx-master/conf/x-waf/mobdebug.lua'
	no file '/usr/local/lib/lua/mobdebug.lua'
	no file './mobdebug.lua'
	no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug/init.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug/init.lua'
	no file './mobdebug.so'
	no file '/usr/local/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/LuaJIT/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: in main chunk, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/hello"
2022/11/23 10:48:10 [error] 9568#0: *2 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: module 'mobdebug' not found:
	no field package.preload['mobdebug']
	no file '/cygdrive/d/code1/nginx-master/conf/x-waf/mobdebug.lua'
	no file '/usr/local/lib/lua/mobdebug.lua'
	no file './mobdebug.lua'
	no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug/init.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug/init.lua'
	no file './mobdebug.so'
	no file '/usr/local/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/LuaJIT/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: in main chunk, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/hello"
2022/11/23 10:48:31 [error] 9568#0: *3 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: module 'mobdebug' not found:
	no field package.preload['mobdebug']
	no file '/cygdrive/d/code1/nginx-master/conf/x-waf/mobdebug.lua'
	no file '/usr/local/lib/lua/mobdebug.lua'
	no file './mobdebug.lua'
	no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug/init.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug/init.lua'
	no file './mobdebug.so'
	no file '/usr/local/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/LuaJIT/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: in main chunk, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/11/23 10:48:31 [error] 9568#0: *3 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: module 'mobdebug' not found:
	no field package.preload['mobdebug']
	no file '/cygdrive/d/code1/nginx-master/conf/x-waf/mobdebug.lua'
	no file '/usr/local/lib/lua/mobdebug.lua'
	no file './mobdebug.lua'
	no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug/init.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug/init.lua'
	no file './mobdebug.so'
	no file '/usr/local/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/LuaJIT/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: in main chunk, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/11/23 10:48:31 [error] 9568#0: *4 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: module 'mobdebug' not found:
	no field package.preload['mobdebug']
	no file '/cygdrive/d/code1/nginx-master/conf/x-waf/mobdebug.lua'
	no file '/usr/local/lib/lua/mobdebug.lua'
	no file './mobdebug.lua'
	no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug/init.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug/init.lua'
	no file './mobdebug.so'
	no file '/usr/local/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/LuaJIT/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: in main chunk, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2022/11/23 10:48:31 [error] 9568#0: *4 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: module 'mobdebug' not found:
	no field package.preload['mobdebug']
	no file '/cygdrive/d/code1/nginx-master/conf/x-waf/mobdebug.lua'
	no file '/usr/local/lib/lua/mobdebug.lua'
	no file './mobdebug.lua'
	no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug/init.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug/init.lua'
	no file './mobdebug.so'
	no file '/usr/local/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/LuaJIT/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: in main chunk, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2022/11/23 10:48:33 [error] 9568#0: *5 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: module 'mobdebug' not found:
	no field package.preload['mobdebug']
	no file '/cygdrive/d/code1/nginx-master/conf/x-waf/mobdebug.lua'
	no file '/usr/local/lib/lua/mobdebug.lua'
	no file './mobdebug.lua'
	no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug/init.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug/init.lua'
	no file './mobdebug.so'
	no file '/usr/local/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/LuaJIT/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: in main chunk, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/11/23 10:48:33 [error] 9568#0: *5 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: module 'mobdebug' not found:
	no field package.preload['mobdebug']
	no file '/cygdrive/d/code1/nginx-master/conf/x-waf/mobdebug.lua'
	no file '/usr/local/lib/lua/mobdebug.lua'
	no file './mobdebug.lua'
	no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug/init.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug/init.lua'
	no file './mobdebug.so'
	no file '/usr/local/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/LuaJIT/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: in main chunk, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/11/23 10:48:33 [error] 9568#0: *6 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: module 'mobdebug' not found:
	no field package.preload['mobdebug']
	no file '/cygdrive/d/code1/nginx-master/conf/x-waf/mobdebug.lua'
	no file '/usr/local/lib/lua/mobdebug.lua'
	no file './mobdebug.lua'
	no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug/init.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug/init.lua'
	no file './mobdebug.so'
	no file '/usr/local/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/LuaJIT/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: in main chunk, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2022/11/23 10:48:33 [error] 9568#0: *6 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: module 'mobdebug' not found:
	no field package.preload['mobdebug']
	no file '/cygdrive/d/code1/nginx-master/conf/x-waf/mobdebug.lua'
	no file '/usr/local/lib/lua/mobdebug.lua'
	no file './mobdebug.lua'
	no file '/usr/local/LuaJIT/share/luajit-2.1.0-beta3/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/share/lua/5.1/mobdebug/init.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug.lua'
	no file '/usr/local/LuaJIT/share/lua/5.1/mobdebug/init.lua'
	no file './mobdebug.so'
	no file '/usr/local/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/LuaJIT/lib/lua/5.1/mobdebug.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:22: in main chunk, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2022/11/23 10:50:41 [error] 9583#0: *1 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/waf.lua:127: attempt to index local 'limit' (a nil value)
stack traceback:
coroutine 0:
	/cygdrive/d/code1/nginx-master/conf/x-waf/waf.lua: in function 'cc_attack_check'
	/cygdrive/d/code1/nginx-master/conf/x-waf/waf.lua:278: in function 'check'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:24: in main chunk, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/11/23 10:50:41 [error] 9583#0: *1 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/waf.lua:127: attempt to index local 'limit' (a nil value)
stack traceback:
coroutine 0:
	/cygdrive/d/code1/nginx-master/conf/x-waf/waf.lua: in function 'cc_attack_check'
	/cygdrive/d/code1/nginx-master/conf/x-waf/waf.lua:278: in function 'check'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:24: in main chunk, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/11/23 10:50:41 [error] 9583#0: *2 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/waf.lua:127: attempt to index local 'limit' (a nil value)
stack traceback:
coroutine 0:
	/cygdrive/d/code1/nginx-master/conf/x-waf/waf.lua: in function 'cc_attack_check'
	/cygdrive/d/code1/nginx-master/conf/x-waf/waf.lua:278: in function 'check'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:24: in main chunk, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2022/11/23 10:50:41 [error] 9583#0: *2 lua entry thread aborted: runtime error: /cygdrive/d/code1/nginx-master/conf/x-waf/waf.lua:127: attempt to index local 'limit' (a nil value)
stack traceback:
coroutine 0:
	/cygdrive/d/code1/nginx-master/conf/x-waf/waf.lua: in function 'cc_attack_check'
	/cygdrive/d/code1/nginx-master/conf/x-waf/waf.lua:278: in function 'check'
	/cygdrive/d/code1/nginx-master/conf/x-waf/access.lua:24: in main chunk, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2022/11/23 12:18:18 [emerg] 9749#0: bind() to 0.0.0.0:80 failed (112: Address already in use)
2022/11/23 12:18:18 [emerg] 9749#0: bind() to 0.0.0.0:80 failed (112: Address already in use)
2022/11/23 12:18:18 [emerg] 9749#0: bind() to 0.0.0.0:80 failed (112: Address already in use)
2022/11/23 12:18:18 [emerg] 9749#0: bind() to 0.0.0.0:80 failed (112: Address already in use)
2022/11/23 12:18:18 [emerg] 9749#0: bind() to 0.0.0.0:80 failed (112: Address already in use)
2022/11/23 12:18:18 [emerg] 9749#0: still could not bind()
